### ISSUE TITLE
can you give me permission to write??

### ISSUE THREAD

**Issue by Driesboy** [caspervanneck/ImagicalMine#3]
- [ ] This issue isn't related to any plugins or plugin related crashes.
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [ ] This issue matches the contributing guidelines - the link is just above the title field.

**Comment by caspervanneck** [comment]
yes

**Comment by caspervanneck** [comment]
@Driesboy

**Comment by caspervanneck** [comment]
@Driesboy uhm wat ben van plan

**Comment by caspervanneck** [comment]
????????????????

**Comment by Driesboy** [comment]
je helpen :)

**Comment by caspervanneck** [comment]
oke (:
