### ISSUE TITLE
How can I help you?

### ISSUE THREAD

**Issue by jdongel2004** [caspervanneck/ImagicalMine#4]
- [ ] This issue isn't related to any plugins or plugin related crashes.
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [ ] This issue matches the contributing guidelines - the link is just above the title field.

## Optional information

 # I want help you. ImagicalMine revival..! I want this.

**Comment by caspervanneck** [comment]
do you know php @jdongel2004

**Comment by jdongel2004** [comment]
@caspervanneck Not bad.

**Comment by caspervanneck** [comment]
https://github.com/ImagicalMine-MP/ImagicalMine/ we are moved i sent you a invite

**Comment by caspervanneck** [comment]
invite is in your mail box @jdongel2004

**Comment by caspervanneck** [comment]
@Driesboy ik hope dat ik je zie in nieuwe group

**Comment by Driesboy** [comment]
aan gekomen
